### PR TITLE
Use --max-idle instead of heartbeats

### PR DESCRIPTION
**Pull request by Cy6erBr4in**
This change will move spydra from using custom heartbeats & self-destruct script to using a new dataproc feature (introduced in current beta) called `cluster scheduled deletion`. More info on the feature here: https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/scheduled-deletion

Note: this transition changes the name and position of configuration parameter responsible for timeout before deletion and format of the value. The parameter responsible for the timeout is now called `max-idle` and is a part of `cluster.options`. The format for the value as described in the documentation:

```Provide the duration in IntegerUnit format, where the unit can be "s, m, h, d" (seconds, minutes, hours, days, respectively). Examples: "30m" or "1d" (30 minutes or 1 day from when the cluster becomes idle).```

The duration should be from the range `10m..14d`

### CODE REVIEW

**Comment by Xeago** [comment]
If one specified the old configuration parameter, what is the behavior? Ignored or error?

**Comment by Cy6erBr4in** [comment]
It'll be ignored since we don't handle it anywhere

**Comment by Cy6erBr4in** [comment]
@Xeago just double checked and it turns out it will fail since we don't ignore unknown fields in json during parsing, so the error will be like this:

```com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "collector_timeout_minutes"...```

**Comment by Cy6erBr4in** [comment]
and obviously the same goes for the second removed parameter: `heartbeat_interval_seconds`

**Comment by Cy6erBr4in** [comment]
It's a better solution for #60

**Pull request merged**
